# Generated by Django 4.1.6 on 2023-02-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_polygon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polygon',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='polygon',
            name='image_base_64',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
