# Generated by Django 4.1.6 on 2023-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_polygon_options_polygon_image_base_64'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polygon',
            options={'ordering': ['num_of_vertices']},
        ),
        migrations.AddField(
            model_name='polygon',
            name='num_of_vertices',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
